[package]
name = "MedRec"
version = "1.0.0"
authors = []

[addresses]
medrec_addr = "0x94091529225773bb5f1f23520535736bb41597cf9dec18c001de0366e0df4182"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "devnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
